---
# tasks file for roles/nginx_deploy
# - name: Remove default.conf
#   ansible.builtin.file:
#     path: /etc/nginx/conf.d/default.conf
#     state: absent

- name: Create ssl dir
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory

- name: Copy ssl certs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/{{ item }}"
  loop:
    - fullchain.pem
    - privkey.pem

- name: Deploy server info HTML
  ansible.builtin.template:
    src: nginx_index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
    backup: true

- name: Deploy Nginx configuration from template
  ansible.builtin.template:
    src: nginx_default.conf.j2
    dest: /etc/nginx/conf.d/{{ inventory_hostname }}.conf
    mode: '0644'
    backup: true
  notify:
    - Restart NGINX
...